CREATE TABLE TodoItems
(
    Id INT PRIMARY KEY NOT NULL,
    OwnerId INT NOT NULL,
    ListId INT NOT NULL FOREIGN KEY REFERENCES TodoLists(Id),
    Name VARCHAR(64) NOT NULL,
    Notes VARCHAR(2048) NOT NULL,
    Reminder DATETIMEOFFSET NULL,
    Priority VARCHAR(8) NOT NULL,
    State VARCHAR(16) NOT NULL,
    ArchiveState VARCHAR(16) NOT NULL,
    Version ROWVERSION NOT NULL
)